PLUGINS:
   DATA_MANAGER:
      -  anura-filesystem  


## data manager to use
DATA_MANAGER: 'FILE_SYSTEM'

DATA_MANAGER_CONFIG:
   #Mongo DataManager options:
   #==========================
   MONGO_STORE: 'mongodb://localhost:27017/test'
   #==========================
   ##FileSystem DataManager Options
   STORE_LOCATION: "./"

#where anura will save the file
#STORE_LOCATION: default to your base folder (where this config is)

## port in witch the anura server will run
SERVER_PORT: 4000
HOST_NAME: 'localhost'

LOG:
   LEVEL: "info"
#   LOG_FILE:
#   ERROR_LOG_FILE:

PUB_SUB:
  TYPE: "redis"
  host: 127.0.0.1
  port: 6379
  auth_pass: "test"
  #TYPE: "none"