## data manager to use
DATA_MANAGER: 'FILE_SYSTEM'

#where anura will save the file 
#STORE_LOCATION:
STORE_LOCATION: "C:/"
## port in witch the anura server will run
SERVER_PORT: 4000
HOST_NAME: 'localhost'

PUB_SUB:
  #TYPE: "redis"
  #HOST: "redis://localhost:6379"
  TYPE: "none"