
## data manager to use
DATA_MANAGER: 'FILE_SYSTEM'
# file system options
HUMAN_READABLE: false
#where anura will save the file 
#STORE_LOCATION:

## port in witch the anura server will run
SERVER_PORT: 4000